-- Replace the placeholder v1 Terms/Privacy text (021_legal_consent.sql) with a complete,
-- generic policy covering how Fana actually works: OCR + AI analysis via Anthropic, spoken
-- audio + voice input via Azure, chat, the credit/free-tier system, and 24-month document
-- retention. Insert as version 2 rather than editing the v1 rows (see LegalDocuments.Version;
-- GetLegalDocumentHandler always serves the highest version per Kind). This is still a
-- generic template, not attorney-reviewed for Israeli law, EU GDPR, or any specific
-- jurisdiction — get it reviewed before relying on it for a real launch, WhatsApp Business
-- Verification, or a payment gateway application. Idempotent: safe to run on every startup.

INSERT INTO LegalDocuments (Id, Kind, Version, BodyHe, BodyAm, BodyEn, EffectiveAt)
VALUES (
    '9b6a1e2a-0002-4a11-8b1a-000000000001', 'terms', 2,
    E'תנאי שימוש באפליקציית Fana\n\n'
    '1. הסכמה לתנאים\n'
    'בפתיחת חשבון או בשימוש באפליקציית Fana, הנך מסכים/ה לתנאי שימוש אלה ולמדיניות הפרטיות שלנו. אם אינך מסכים/ה לתנאים, אנא הימנע/י משימוש בשירות.\n\n'
    '2. מה Fana עושה\n'
    'Fana עוזרת למשתמשים דוברי אמהרית להבין מסמכים רשמיים הכתובים בעברית. אתם מעלים תמונה או קובץ של מסמך; Fana מחלצת את הטקסט (זיהוי טקסט אופטי - OCR), מנתחת אותו באמצעות בינה מלאכותית, ומספקת הסבר בשפה פשוטה בעברית, באמהרית או באנגלית, עם אפשרות להקראה קולית ולצ׳אט שבו ניתן לשאול שאלות המשך.\n\n'
    '3. לא ייעוץ מקצועי\n'
    'ההסברים שמספקת Fana הם כלי עזר כללי להבנה, ואינם ייעוץ משפטי, רפואי, פיננסי או מיסויי, ואינם תחליף לגורם שהנפיק את המסמך. יש לאמת כל דבר דחוף או משמעותי — מועדים, סכומים לתשלום, זכאות — ישירות מול אותו גורם לפני שפועלים על פיו.\n\n'
    '4. כשירות\n'
    'עליך להיות בן/בת 18 ומעלה כדי לפתוח חשבון, או להשתמש בשירות בליווי מבוגר אחראי. הנך אחראי/ת לדיוק המידע שאתה/את מוסר/ת.\n\n'
    '5. המסמכים שלך והתנהגותך\n'
    'יש להעלות רק מסמכים שהם שלך, או שיש לך זכות חוקית לטפל בהם עבור מישהו אחר (לדוגמה, כבן משפחה המסייע לו). אין להעלות מסמכים של אדם זר, ואין להשתמש ב-Fana למטרה בלתי חוקית.\n\n'
    '6. קרדיטים ושימוש חינמי\n'
    'Fana מציעה מספר מוגבל של ניתוחים בחינם; שימוש נוסף עשוי לדרוש קרדיטים, שניתן לרכוש, לקבל במתנה או לקבל ממשתמש אחר, כמתואר באפליקציה. לקרדיטים אין ערך כספי, הם אינם ניתנים להחזר אלא אם נדרש אחרת על פי חוק, וקרדיטים שלא נוצלו אינם פגי תוקף אלא אם צוין אחרת באפליקציה.\n\n'
    '7. ספקים חיצוניים\n'
    'כדי לספק את שירותי זיהוי הטקסט, הניתוח בבינה מלאכותית וההקראה הקולית, Fana שולחת את טקסט המסמך הרלוונטי, ולצורך קלט/פלט קולי גם קטעי שמע, לספקי בינה מלאכותית חיצוניים (כיום Anthropic לניתוח טקסט ו-Microsoft Azure לשירותי קול). ספקים אלה מעבדים את המידע בהתאם לתנאים שלהם על מנת להחזיר תוצאה ל-Fana; Fana אינה מתירה להם להשתמש במידע שלך לאימון המודלים שלהם מעבר לנדרש לצורך אספקת השירות.\n\n'
    '8. זמינות ושינויים\n'
    'Fana מסופקת כפי שהיא (AS-IS) ובכפוף לזמינות. אנו רשאים להוסיף, לשנות או להסיר תכונות, ולהשעות או להפסיק את השירות, בכל עת, ותוך מתן הודעה סבירה מראש כאשר ניתן.\n\n'
    '9. סיום שימוש\n'
    'ניתן להפסיק את השימוש ב-Fana ולמחוק את החשבון בכל עת דרך עמוד הפרופיל. אנו רשאים להשעות או לסגור חשבון המפר תנאים אלה או המשמש למטרה בלתי חוקית או פוגענית.\n\n'
    '10. הגבלת אחריות\n'
    'במידה המרבית המותרת על פי חוק, Fana ומפעיליה לא יישאו באחריות לנזקים עקיפים, אגביים או תוצאתיים הנובעים משימושך בשירות, לרבות החלטות שהתקבלו בהתבסס על הסבר שנוצר על ידי בינה מלאכותית. אין באמור לעיל כדי להגביל אחריות שלא ניתן להחריג על פי הדין החל.\n\n'
    '11. הדין החל\n'
    'תנאים אלה כפופים לדיני מדינת ישראל, מבלי להתחשב בכללי ברירת הדין, וכל מחלוקת תובא לסמכות השיפוט הבלעדית של בתי המשפט המוסמכים בישראל.\n\n'
    '12. שינויים בתנאים אלה\n'
    'אנו רשאים לעדכן תנאים אלו מעת לעת. שינויים מהותיים יפורסמו בעמוד זה עם מספר גרסה חדש, והמשך השימוש ב-Fana לאחר כניסת השינוי לתוקף מהווה הסכמה לתנאים המעודכנים.\n\n'
    '13. יצירת קשר\n'
    'לשאלות בנוגע לתנאים אלה ניתן לפנות לכתובת התמיכה המופיעה בעמוד העזרה.',
    E'የFana መተግበሪያ የአገልግሎት ውሎች\n\n'
    '1. ውሎችን መቀበል\n'
    'መለያ በመክፈት ወይም Fana ን በመጠቀም፣ በእነዚህ የአገልግሎት ውሎች እና በእኛ የግላዊነት ፖሊሲ ይስማማሉ። ካልተስማሙ፣ እባክዎ አገልግሎቱን አይጠቀሙ።\n\n'
    '2. Fana ምን እንደሚያደርግ\n'
    'Fana አማርኛ ተናጋሪ ተጠቃሚዎች በዕብራይስጥ የተጻፉ ኦፊሴላዊ ሰነዶችን እንዲረዱ ይረዳል። የሰነድ ፎቶ ወይም ፋይል ይሰቅላሉ፤ Fana ጽሑፉን ያወጣል (የጽሑፍ ማወቂያ - OCR)፣ በአርቴፊሻል ኢንተለጀንስ ይተነትነዋል፣ እና በዕብራይስጥ፣ በአማርኛ ወይም በእንግሊዝኛ ቀላል ማብራሪያ ይሰጣል፣ በተጨማሪ በድምጽ የማንበብ አማራጭ እና ተጨማሪ ጥያቄዎችን መጠየቅ የሚችሉበት ውይይት (chat) ያካትታል።\n\n'
    '3. ሙያዊ ምክር አይደለም\n'
    'የFana ማብራሪያዎች አጠቃላይ የመረዳት እርዳታ ናቸው፣ አስገዳጅ የሕግ፣ የሕክምና፣ የፋይናንስ ወይም የግብር ምክር አይደሉም፣ እና ሰነዱን ላወጣው አካል ምትክ አይደሉም። አስቸኳይ ወይም ወሳኝ የሆነ ማንኛውንም ነገር — የጊዜ ገደቦች፣ የሚከፈል ገንዘብ መጠን፣ ብቁነት — ከመተግበርዎ በፊት በቀጥታ ከዚያ አካል ጋር ማረጋገጥ አለብዎት።\n\n'
    '4. ብቁነት\n'
    'መለያ ለመክፈት 18 ዓመት እና ከዚያ በላይ መሆን አለብዎት፣ ወይም አገልግሎቱን በኃላፊነት ባለው አዋቂ ታጅበው መጠቀም አለብዎት። ስለሚያቀርቡት መረጃ ትክክለኛነት ኃላፊነት አለብዎት።\n\n'
    '5. የእርስዎ ሰነዶች እና ባህሪ\n'
    'የእርስዎ የሆኑ ወይም ለሌላ ሰው (ለምሳሌ፣ የቤተሰብ አባል ሆነው የሚረዷቸው) ወክለው ለማስኬድ ሕጋዊ መብት ያላችሁባቸውን ሰነዶች ብቻ ይስቀሉ። የማያውቁት ሰው ሰነድ አይስቀሉ፣ Fana ንም ለማንኛውም ሕገ-ወጥ ዓላማ አይጠቀሙ።\n\n'
    '6. ክሬዲቶች እና ነጻ አጠቃቀም\n'
    'Fana የተወሰነ ቁጥር ያላቸው ነጻ ትንተናዎችን ትሰጣለች፤ ተጨማሪ አጠቃቀም በመተግበሪያው ውስጥ እንደተገለጸው ሊገዙ፣ ሊሰጡ ወይም ከሌላ ተጠቃሚ በስጦታ ሊገኙ የሚችሉ ክሬዲቶችን ሊፈልግ ይችላል። ክሬዲቶች የገንዘብ ዋጋ የላቸውም፣ በሕግ ካልተጠየቀ በስተቀር ተመላሽ አይደረጉም፣ እና ባልተጠቀሙት ክሬዲቶች በመተግበሪያው ላይ በተለየ ካልተገለጸ በስተቀር የጊዜ ገደብ የላቸውም።\n\n'
    '7. የሶስተኛ ወገን አገልግሎት ሰጪዎች\n'
    'የጽሑፍ ማወቂያ፣ የአርቴፊሻል ኢንተለጀንስ ትንተና እና የድምጽ አገልግሎቶችን ለማቅረብ፣ Fana ተዛማጅ የሰነድ ጽሑፍን፣ እና ለድምጽ ግቤት/ውጤት ደግሞ የድምጽ ፋይሎችን፣ ለሶስተኛ ወገን የአርቴፊሻል ኢንተለጀንስ አገልግሎት ሰጪዎች ትልካለች (በአሁኑ ጊዜ Anthropic ለጽሑፍ ትንተና እና Microsoft Azure ለድምጽ አገልግሎቶች)። እነዚህ አገልግሎት ሰጪዎች ውጤት ለFana ለመመለስ በራሳቸው ውሎች መሠረት መረጃውን ያስኬዳሉ፤ Fana አገልግሎቱን ለማቅረብ ከሚያስፈልገው በላይ የእርስዎን መረጃ ሞዴሎቻቸውን ለማሰልጠን እንዲጠቀሙ አትፈቅድላቸውም።\n\n'
    '8. አገልግሎት መገኘት እና ለውጦች\n'
    'Fana የምትቀርበው እንዳለችው (as-is) እና እንደተገኘችው ነው። ማንኛውንም ጊዜ ባህሪያትን ልንጨምር፣ ልንቀይር ወይም ልናስወግድ እንችላለን፣ እና አገልግሎቱን ልናቋርጥ ወይም ልናቆም እንችላለን፣ ይህም ሲቻል በምክንያታዊ ማስታወቂያ ጋር ነው።\n\n'
    '9. አገልግሎት ማቆም\n'
    'በማንኛውም ጊዜ Fana ን መጠቀም አቁመው በመገለጫ ገጹ በኩል መለያዎን መሰረዝ ይችላሉ። እነዚህን ውሎች የሚጥስ ወይም ለሕገ-ወጥ ወይም አላግባብ ዓላማ የሚያገለግል መለያ ልናቋርጥ ወይም ልንዘጋ እንችላለን።\n\n'
    '10. የኃላፊነት ገደብ\n'
    'በሕግ በተፈቀደው ከፍተኛ መጠን፣ Fana እና አንቀሳቃሾቿ አገልግሎቱን ከመጠቀምዎ የሚነሱ ቀጥተኛ ያልሆኑ፣ ድንገተኛ ወይም ተከታይ ጉዳቶች ኃላፊነት አይወስዱም፣ በአርቴፊሻል ኢንተለጀንስ በተፈጠረ ማብራሪያ ላይ ተመስርተው የተወሰኑ ውሳኔዎችን ጨምሮ። በዚህ ውስጥ ያለው ምንም ነገር በተፈጻሚ ሕግ መሠረት ሊገለል የማይችል ኃላፊነትን አይገድብም።\n\n'
    '11. የሚመለከተው ሕግ\n'
    'እነዚህ ውሎች በእስራኤል ግዛት ሕጎች ይመራሉ፣ የሕግ ግጭት መርሆችን ከግምት ውስጥ ሳያስገባ፣ እና ማንኛውም አለመግባባት በእስራኤል ብቁ ፍርድ ቤቶች ብቸኛ ስልጣን ስር ይሆናል።\n\n'
    '12. በእነዚህ ውሎች ላይ የሚደረጉ ለውጦች\n'
    'እነዚህን ውሎች ከጊዜ ወደ ጊዜ ልናዘምናቸው እንችላለን። ጉልህ ለውጦች በአዲስ ስሪት ቁጥር በዚህ ገጽ ላይ ይታተማሉ፣ ለውጡ ከጸናበት ጊዜ በኋላ Fana ን መቀጠል መጠቀም የተሻሻሉትን ውሎች መቀበልን ያመለክታል።\n\n'
    '13. አድራሻ\n'
    'ስለ እነዚህ ውሎች ጥያቄዎች ካሉዎት በእገዛ ገጹ ላይ ወዳለው የድጋፍ አድራሻ ይላኩ።',
    E'Fana Terms of Service\n\n'
    '1. Acceptance of Terms\n'
    'By creating an account or using Fana, you agree to these Terms of Service and to our Privacy Policy. If you do not agree, please do not use the service.\n\n'
    '2. What Fana Does\n'
    'Fana helps Amharic-speaking users understand official documents written in Hebrew. You upload a photo or file of a document; Fana extracts the text (OCR), analyzes it with artificial intelligence, and gives you a plain-language explanation in Hebrew, Amharic, or English, with optional spoken audio and a chat you can ask follow-up questions in.\n\n'
    '3. Not Professional Advice\n'
    'The explanations Fana provides are a general aid to understanding, not legal, medical, financial, or tax advice, and not a substitute for the institution that issued the document. Always confirm anything time-sensitive or consequential — deadlines, amounts owed, eligibility — directly with that institution before acting on it.\n\n'
    '4. Eligibility\n'
    'You must be 18 or older to create an account, or use the service together with a responsible adult. You are responsible for the accuracy of the information you provide.\n\n'
    '5. Your Documents and Conduct\n'
    'Only upload documents that are yours, or that you have the legal right to process on behalf of someone else (for example, as a family member helping them). Do not upload a stranger''s documents, and do not use Fana for any unlawful purpose.\n\n'
    '6. Credits and Free Usage\n'
    'Fana provides a limited number of free analyses; additional usage may require credits, which can be purchased, granted, or gifted by another user, as described in the app. Credits have no cash value, are not refundable except where required by law, and unused credits do not expire unless stated otherwise in the app.\n\n'
    '7. Third-Party Providers\n'
    'To provide OCR, AI analysis, and voice features, Fana sends the relevant document text, and audio for voice input/output, to third-party AI providers (currently Anthropic for text analysis and Microsoft Azure for speech). These providers process the data under their own terms in order to return a result to Fana; Fana does not permit them to use your data to train their models beyond what is needed to deliver the service.\n\n'
    '8. Availability and Changes\n'
    'Fana is provided on an as-is, as-available basis. We may add, change, or remove features, and may suspend or discontinue the service, at any time, with reasonable notice where practical.\n\n'
    '9. Termination\n'
    'You may stop using Fana and delete your account at any time from the Profile page. We may suspend or terminate an account that violates these Terms or is used for an unlawful or abusive purpose.\n\n'
    '10. Limitation of Liability\n'
    'To the maximum extent permitted by law, Fana and its operators are not liable for indirect, incidental, or consequential damages arising from your use of the service, including decisions made based on an AI-generated explanation. Nothing in these Terms limits liability that cannot be excluded under applicable law.\n\n'
    '11. Governing Law\n'
    'These Terms are governed by the laws of the State of Israel, without regard to conflict-of-law principles, and any dispute will be subject to the exclusive jurisdiction of the competent courts of Israel.\n\n'
    '12. Changes to These Terms\n'
    'We may update these Terms from time to time. Material changes will be published on this page under a new version number, and continued use of Fana after a change takes effect constitutes acceptance of the updated Terms.\n\n'
    '13. Contact\n'
    'Questions about these Terms can be sent to the support address listed on the Help page.',
    now()
)
ON CONFLICT (Kind, Version) DO NOTHING;

INSERT INTO LegalDocuments (Id, Kind, Version, BodyHe, BodyAm, BodyEn, EffectiveAt)
VALUES (
    '9b6a1e2a-0002-4a11-8b1a-000000000002', 'privacy', 2,
    E'מדיניות פרטיות של Fana\n\n'
    '1. מידע שאנו אוספים\n'
    'אנו אוספים: כתובת אימייל ופרטי חשבון; תמונות או קבצים של מסמכים שהעליתם; הטקסט שחולץ מהם והניתוח שנוצר עבורם באמצעות בינה מלאכותית; היסטוריית הצ׳אט על כל מסמך; ונתוני שימוש בסיסיים (כגון שימוש בתכונות ורישומי שגיאות) המשמשים להפעלת השירות ולשיפורו.\n\n'
    '2. כיצד אנו משתמשים במידע\n'
    'אנו משתמשים במידע כדי להפעיל את השירות (חילוץ טקסט, ניתוח, הקראה קולית, מענה בצ׳אט), לנהל את חשבונך ואת יתרת הקרדיטים שלך, להשיב לפניות תמיכה, ולשפר את הדיוק והאמינות של Fana. אנו לא משתמשים בתוכן המסמכים שלך לצורכי פרסום, ואיננו מוכרים מידע אישי לצדדים שלישיים.\n\n'
    '3. מעבדי מידע חיצוניים\n'
    'כדי לספק את שירותי ה-OCR, הניתוח בבינה מלאכותית וההקראה הקולית, טקסט המסמך הרלוונטי וקטעי שמע נשלחים למעבדים חיצוניים, כיום Anthropic (ניתוח טקסט) ו-Microsoft Azure (המרת טקסט לדיבור ודיבור לטקסט). ספקים אלה פועלים כמעבדי מידע מטעם Fana, ומוגבלים חוזית משימוש במידע שלך למטרות שאינן אספקת השירות ל-Fana.\n\n'
    '4. שמירת מידע\n'
    'מסמכים שהועלו, הטקסט שחולץ מהם והניתוח שלהם נשמרים עד 24 חודשים מרגע ההעלאה, ולאחר מכן נמחקים אוטומטית, אלא אם תבחרו למחוק אותם קודם לכן דרך האפליקציה. היסטוריית הצ׳אט על מסמך נמחקת יחד עם אותו מסמך.\n\n'
    '5. הזכויות שלך\n'
    'ניתן לבקש בכל עת עותק של המידע השמור עליך, או למחוק לצמיתות את חשבונך ואת תוכנו, דרך עמוד הפרופיל או בפנייה לתמיכה. מחיקה היא סופית ואינה ניתנת לביטול.\n\n'
    '6. אבטחת מידע\n'
    'מידע מתוך מסמכים, לרבות מסמכים בנקאיים, ממשלתיים ורפואיים, מטופל כמידע רגיש. אנו נוקטים באמצעים טכניים וארגוניים סבירים — לרבות חיבורים מוצפנים ובקרות גישה — כדי להגן עליו, אך אין ביכולתו של שירות מקוון כלשהו להבטיח אבטחה מוחלטת.\n\n'
    '7. פרטיות קטינים\n'
    'Fana מיועדת למשתמשים בני 18 ומעלה, או לשימוש בליווי מבוגר אחראי. איננו אוספים ביודעין מידע אישי מילדים המשתמשים בשירות ללא פיקוח.\n\n'
    '8. העברת מידע בין-לאומית\n'
    'מאחר שחלק מהמעבדים שלנו מפעילים תשתיות מחוץ לישראל, ייתכן שהמידע שלך יעובד במדינות אחרות. אנו בוחרים מעבדים השומרים על אמצעי הגנת פרטיות נאותים.\n\n'
    '9. שינויים במדיניות זו\n'
    'אנו רשאים לעדכן מדיניות פרטיות זו מעת לעת. שינויים מהותיים יפורסמו בעמוד זה עם מספר גרסה חדש.\n\n'
    '10. יצירת קשר\n'
    'לשאלות בנוגע למדיניות פרטיות זו, או לבקשות לעיון במידע או למחיקתו, ניתן לפנות לכתובת התמיכה המופיעה בעמוד העזרה.',
    E'የFana ግላዊነት ፖሊሲ\n\n'
    '1. የምንሰበስበው መረጃ\n'
    'የምንሰበስበው መረጃ፦ የኢሜይል አድራሻዎ እና የመለያ ዝርዝሮች፤ የሰቀሏቸው የሰነድ ፎቶዎች ወይም ፋይሎች፤ ከነሱ የተወጣው ጽሑፍ እና በአርቴፊሻል ኢንተለጀንስ የተፈጠረው ትንተናቸው፤ በእያንዳንዱ ሰነድ ላይ ያለው የውይይት ታሪክ፤ እና አገልግሎቱን ለማስኬድ እና ለማሻሻል የሚያገለግል መሠረታዊ የአጠቃቀም መረጃ (እንደ ባህሪ አጠቃቀም እና የስህተት መዝገቦች)።\n\n'
    '2. መረጃውን እንዴት እንደምንጠቀም\n'
    'መረጃውን አገልግሎቱን ለማስኬድ (ጽሑፍ ማወቂያ፣ ትንተና፣ በድምጽ ማንበብ፣ በውይይት መልስ መስጠት)፣ መለያዎን እና የክሬዲት ሂሳብዎን ለማስተዳደር፣ ለድጋፍ ጥያቄዎች ምላሽ ለመስጠት፣ እና የFana ን ትክክለኛነት እና አስተማማኝነት ለማሻሻል እንጠቀማለን። የሰነድ ይዘትዎን ለማስታወቂያ ዓላማ አንጠቀምም፣ እና የግል መረጃን ለሶስተኛ ወገኖች አንሸጥም።\n\n'
    '3. የሶስተኛ ወገን አስኪያጆች\n'
    'የOCR፣ የአርቴፊሻል ኢንተለጀንስ ትንተና እና የድምጽ ባህሪያትን ለማቅረብ፣ ተዛማጅ የሰነድ ጽሑፍ እና የድምጽ ፋይሎች ለሶስተኛ ወገን አስኪያጆች ይላካሉ፣ በአሁኑ ጊዜ Anthropic (የጽሑፍ ትንተና) እና Microsoft Azure (ጽሑፍ ወደ ድምጽ እና ድምጽ ወደ ጽሑፍ)። እነዚህ አገልግሎት ሰጪዎች Fana ን ወክለው እንደ አስኪያጆች ይሰራሉ፣ እና ውል በማድረግ የእርስዎን መረጃ ለFana አገልግሎት ከማቅረብ ውጪ ለሌላ ዓላማ እንዳይጠቀሙ ተገድበዋል።\n\n'
    '4. የመረጃ ማቆያ ጊዜ\n'
    'የተሰቀሉ ሰነዶች፣ የተወጣው ጽሑፋቸው እና ትንተናቸው ከተሰቀሉበት ጊዜ ጀምሮ እስከ 24 ወራት ይቀመጣሉ፣ ከዚያ በኋላ በራስ-ሰር ይሰረዛሉ፣ ካልፈለጉ በስተቀር ቀድመው በመተግበሪያው በኩል ሊሰርዟቸው ይችላሉ። በሰነድ ላይ ያለው የውይይት ታሪክ ከዚያ ሰነድ ጋር አብሮ ይሰረዛል።\n\n'
    '5. የእርስዎ መብቶች\n'
    'በማንኛውም ጊዜ ስለ እርስዎ የተቀመጠውን መረጃ ቅጂ መጠየቅ፣ ወይም መለያዎን እና ይዘቱን ሙሉ በሙሉ በመገለጫ ገጹ በኩል ወይም ድጋፍን በማነጋገር ለዘላለም መሰረዝ ይችላሉ። መሰረዝ የመጨረሻ ነው እና ሊቀለበስ አይችልም።\n\n'
    '6. የመረጃ ደህንነት\n'
    'የሰነድ መረጃ፣ የባንክ፣ የመንግስት እና የጤና ሰነዶችን ጨምሮ፣ እንደ ስሱ መረጃ ይታያል። ለመጠበቅ ምክንያታዊ የቴክኒክ እና የድርጅት እርምጃዎችን — የተመሰጠሩ ግንኙነቶችን እና የመዳረሻ ቁጥጥሮችን ጨምሮ — እንጠቀማለን፣ ነገር ግን ምንም የመስመር ላይ አገልግሎት ፍጹም ደህንነትን ዋስትና ሊሰጥ አይችልም።\n\n'
    '7. የልጆች ግላዊነት\n'
    'Fana ለ18 ዓመት እና ከዚያ በላይ ለሆኑ ተጠቃሚዎች፣ ወይም በኃላፊነት ባለው አዋቂ ታጅበው ለሚጠቀሙ የታሰበ ነው። ያለ ክትትል አገልግሎቱን ከሚጠቀሙ ልጆች ወዲያውኑ ግላዊ መረጃ ሆነን አንሰበስብም።\n\n'
    '8. ዓለም አቀፍ የመረጃ ዝውውር\n'
    'አንዳንድ አስኪያጆቻችን ከእስራኤል ውጪ መሠረተ ልማት ስለሚያንቀሳቅሱ፣ የእርስዎ መረጃ በሌሎች ሀገራት ሊስተናገድ ይችላል። ተገቢ የመረጃ ጥበቃ ጥንቃቄዎችን የሚያደርጉ አስኪያጆችን እንመርጣለን።\n\n'
    '9. በዚህ ፖሊሲ ላይ የሚደረጉ ለውጦች\n'
    'ይህን የግላዊነት ፖሊሲ ከጊዜ ወደ ጊዜ ልናዘምነው እንችላለን። ጉልህ ለውጦች በአዲስ ስሪት ቁጥር በዚህ ገጽ ላይ ይታተማሉ።\n\n'
    '10. አድራሻ\n'
    'ስለዚህ የግላዊነት ፖሊሲ ጥያቄዎች፣ ወይም መረጃዎን ለመድረስ ወይም ለመሰረዝ ጥያቄዎች ካሉዎት፣ በእገዛ ገጹ ላይ ወዳለው የድጋፍ አድራሻ ይላኩ።',
    E'Fana Privacy Policy\n\n'
    '1. Information We Collect\n'
    'We collect: your email address and account details; the document photos or files you upload; the text extracted from them and their AI-generated analysis; your chat history on each document; and basic usage data (such as feature usage and error logs) used to operate and improve the service.\n\n'
    '2. How We Use Your Information\n'
    'We use this information to operate the service (text extraction, analysis, spoken audio, chat answers), to maintain your account and credit balance, to respond to support requests, and to improve Fana''s accuracy and reliability. We do not use your document content for advertising, and we do not sell your personal information to third parties.\n\n'
    '3. Third-Party Processors\n'
    'To deliver OCR, AI analysis, and voice features, relevant document text and audio are sent to third-party processors, currently Anthropic (text analysis) and Microsoft Azure (text-to-speech and speech-to-text). These providers act as processors on Fana''s behalf and are contractually restricted from using your data for purposes other than providing the service to Fana.\n\n'
    '4. Data Retention\n'
    'Uploaded documents, their extracted text, and their analysis are retained for up to 24 months from upload and then automatically deleted, unless you delete them sooner yourself from within the app. Chat history on a document is deleted together with that document.\n\n'
    '5. Your Rights\n'
    'You can request a copy of the information stored about you, or permanently delete your account and its contents, at any time from the Profile page, or by contacting support. Deletion is permanent and cannot be undone.\n\n'
    '6. Data Security\n'
    'Document data, including bank, government, and healthcare documents, is treated as sensitive information. We use reasonable technical and organizational measures — including encrypted connections and access controls — to protect it, but no online service can guarantee absolute security.\n\n'
    '7. Children''s Privacy\n'
    'Fana is intended for users 18 and older, or for use together with a responsible adult. We do not knowingly collect personal information from children using the service unsupervised.\n\n'
    '8. International Data Transfer\n'
    'Because some of our processors operate infrastructure outside Israel, your data may be processed in other countries. We select processors that maintain appropriate data-protection safeguards.\n\n'
    '9. Changes to This Policy\n'
    'We may update this Privacy Policy from time to time. Material changes will be published on this page under a new version number.\n\n'
    '10. Contact\n'
    'Questions about this Privacy Policy, or requests to access or delete your data, can be sent to the support address listed on the Help page.',
    now()
)
ON CONFLICT (Kind, Version) DO NOTHING;
