"use client";

import { useEffect, useRef, useState } from "react";
import { Volume2 } from "lucide-react";
import { useLanguage } from "@/lib/language-context";
import { useFocusTrap } from "@/lib/useFocusTrap";
import { LANGUAGES } from "@/lib/types";
import { Flag } from "@/components/ui/Flag";

// Pre-generated by scripts/generate-ui-audio.mjs (feature #2 slice — only these three clips are
// pre-generated so far; the full ~40-key spoken UI is deferred, see the implementation plan).
const GATE_CLIPS = ["/audio/gate/he.mp3", "/audio/gate/am.mp3", "/audio/gate/en.mp3"];

/**
 * Full-screen, blocking language picker shown before anything else on a visitor's first
 * visit (no stored `lang`). The app otherwise defaults to Hebrew, which is unreadable to
 * the Amharic-speaking users it's built for — silently guessing from navigator.language
 * is avoided on purpose (cheap Android phones in Israel often report "he" regardless of
 * the owner's language), so this asks once, in every script at once, and remembers it.
 */
export function LanguageGate() {
  const { languageChosen, setLanguage } = useLanguage();
  // No onEscape — blocking by design (there is no "cancel" state; a language must be chosen).
  const trapRef = useFocusTrap(!languageChosen);
  const [playing, setPlaying] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  // `onerror` (a genuinely broken/missing file) skips ahead so one bad clip doesn't stall the
  // rest. A rejected play() promise is different — almost always the browser's autoplay policy
  // blocking this specific call — and is NOT treated as "skip ahead": chaining past a block used
  // to cascade into he.mp3 failing while am.mp3/en.mp3 (attempted moments later, once some
  // browsers' autoplay heuristics had shifted) went on to play anyway, which sounded like a
  // random language dropping out rather than a clean "nothing played". Stopping the whole
  // sequence on the first block instead means either all three play, or silence — never a
  // confusing partial set — and the always-visible Listen button (a real user gesture, reliably
  // unblocked) is what the user reaches for either way.
  const playAll = (clips: string[], onBlocked: () => void) => {
    if (clips.length === 0) {
      setPlaying(false);
      return;
    }
    const [first, ...rest] = clips;
    const audio = new Audio(first);
    audioRef.current = audio;
    audio.onended = () => playAll(rest, onBlocked);
    audio.onerror = () => playAll(rest, onBlocked);
    audio.play().catch(onBlocked);
  };

  useEffect(() => {
    if (languageChosen) return;
    // Best-effort autoplay — this is a genuine first visit, so there is usually no prior user
    // gesture and the browser will reject it; that's expected and silently stops the sequence
    // (see playAll above). On Android with existing media-engagement history it sometimes
    // succeeds in full (free upside). The Listen button below is the reliable path either way.
    setPlaying(true);
    playAll(GATE_CLIPS, () => setPlaying(false));
    return () => audioRef.current?.pause();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [languageChosen]);

  if (languageChosen) return null;

  const listen = () => {
    audioRef.current?.pause();
    setPlaying(true);
    // A real click is a genuine user gesture, so play() should reliably succeed here — but stop
    // cleanly (rather than skip ahead) on the off chance it's still blocked, for the same reason
    // the autoplay attempt does: a silent stop reads better than an unexplained missing language.
    playAll(GATE_CLIPS, () => setPlaying(false));
  };

  return (
    <div
      data-language-gate
      data-a11y-fixed
      role="dialog"
      aria-modal="true"
      aria-label="בחרו שפה · ቋንቋ ይምረጡ · Choose your language"
      className="fixed inset-0 z-[60] flex items-center justify-center bg-white p-6 dark:bg-gray-900"
    >
      <div ref={trapRef} className="w-full max-w-sm text-center">
        <h1 className="mb-4 text-xl font-bold text-gray-900 dark:text-gray-100">
          בחרו שפה · ቋንቋ ይምረጡ · Choose your language
        </h1>
        <button
          onClick={listen}
          disabled={playing}
          className="mb-6 inline-flex items-center gap-2 rounded-full border border-gray-200 bg-white px-4 py-2 text-sm font-semibold text-brand shadow-soft disabled:opacity-60 dark:border-gray-700 dark:bg-gray-800"
        >
          <Volume2 className="h-4 w-4" />
          🔊 שמעו · ያዳምጡ · Listen
        </button>
        <div className="flex flex-col gap-3">
          {LANGUAGES.map((l) => (
            <button
              key={l.code}
              onClick={() => setLanguage(l.code)}
              className="flex min-h-[72px] items-center gap-4 rounded-2xl border border-gray-200 bg-white px-6 py-4 text-start shadow-soft transition-transform hover:scale-[1.02] active:scale-100 dark:border-gray-700 dark:bg-gray-800"
            >
              <Flag code={l.flag} size={32} />
              <span className="text-2xl font-bold text-gray-900 dark:text-gray-100">{l.label}</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
