// Shared frontend types, mirroring the backend DTOs.

export type Language = "he" | "am" | "en";

// `flag` is an ISO country code used to load a flag image (emoji flags don't render on Windows).
export const LANGUAGES: { code: Language; label: string; rtl: boolean; flag: string }[] = [
  { code: "he", label: "עברית", rtl: true, flag: "il" },
  { code: "am", label: "አማርኛ", rtl: false, flag: "et" }, // Amharic (Ethiopic) is written LTR.
  { code: "en", label: "English", rtl: false, flag: "gb" },
];

// Only Hebrew is rendered right-to-left.
export function isRtl(language: Language): boolean {
  return language === "he";
}

// Maps frontend language codes to the backend Language enum (Hebrew=0, Amharic=1, English=2).
export const LANGUAGE_ENUM: Record<Language, number> = { he: 0, am: 1, en: 2 };

// Which passage of a spoken analysis to synthesize — mirrors the backend SpokenSection enum.
// Full plays the whole walkthrough; a specific section drives a per-card "read just this" button.
export type SpokenSectionKey = "Full" | "Summary" | "Explanation" | "KeyPoints" | "Actions" | "Deadlines";
export const SPOKEN_SECTION: Record<SpokenSectionKey, number> = {
  Full: 0,
  Summary: 1,
  Explanation: 2,
  KeyPoints: 3,
  Actions: 4,
  Deadlines: 5,
};

export type UrgencyLevel = "Low" | "Medium" | "High" | "Critical";

// A text generated by the backend in all three languages.
export interface LocalizedText {
  he: string;
  am: string;
  en: string;
}

// The chosen language's text, falling back to another language if it's blank.
export function loc(text: LocalizedText | undefined, language: Language): string {
  if (!text) return "";
  const order: Record<Language, Language[]> = {
    am: ["am", "en", "he"],
    en: ["en", "he", "am"],
    he: ["he", "en", "am"],
  };
  for (const l of order[language]) {
    if (text[l]?.trim()) return text[l];
  }
  return "";
}

// Document institution categories, mirroring the backend DocumentCategory enum (sent as ints).
export const DOCUMENT_CATEGORY = {
  Government: 0,
  Bank: 1,
  Insurance: 2,
  Employment: 3,
  Healthcare: 4,
  Municipality: 5,
  Other: 6,
} as const;

// Urgency string → backend enum int (the wire uses ints, like ChatMessage.role).
export const URGENCY_ENUM: Record<UrgencyLevel, number> = { Low: 0, Medium: 1, High: 2, Critical: 3 };

// The API serializes enums as ints on the wire, but AnalysisResult['urgencyLevel'] types it as a
// string — tolerate both instead of duplicating this normalization in every component that reads
// urgency (AnalysisCard, AnalysisVerdict, ReferralBlock all needed it independently before this).
export function urgencyIndexOf(urgencyLevel: UrgencyLevel | number): number {
  return typeof urgencyLevel === "number" ? urgencyLevel : URGENCY_ENUM[urgencyLevel] ?? 0;
}

// A vetted professional shown as a sponsored referral.
export interface Provider {
  id: string;
  category: number;
  displayName: string;
  phone: string | null;
  whatsApp: string | null;
  city: string | null;
  blurb: LocalizedText;
}

// The exact Hebrew sentence to say at a counter or on the phone for a required action, plus
// what it means in the reader's own language. `say` is deliberately a plain string, not
// LocalizedText — it IS Hebrew by definition; localizing it would defeat the point (see
// PhraseCard.tsx). Currently authored by hand only on the /sample fixture — real analyses
// don't populate this yet (see the deferred backend-schema slice in the implementation plan).
export interface HebrewPhrase {
  say: string;
  meaning: LocalizedText;
}

export interface AnalysisResult {
  summary: LocalizedText;
  documentType: LocalizedText;
  // AI-classified institution category (DocumentCategory int) used to match referrals.
  category?: number;
  urgencyLevel: UrgencyLevel;
  keyPoints: LocalizedText[];
  requiredActions: {
    description: LocalizedText;
    isMandatory: boolean;
    hebrewPhrase?: HebrewPhrase;
    contactPhone?: string | null;
  }[];
  deadlines: { date: string | null; description: LocalizedText }[];
  explanation: LocalizedText;
}

// Background OCR pipeline state (see backend DocumentProcessor). Sent as an int on the wire
// (0=Pending, 1=Processing, 2=Ready, 3=Failed) like every other backend enum except
// AnalysisResult.urgencyLevel — see the note there.
export const DOCUMENT_STATUS = { Pending: 0, Processing: 1, Ready: 2, Failed: 3 } as const;

export interface DocumentSummary {
  id: string;
  fileName: string;
  contentType: string;
  uploadedAt: string;
  hasAnalysis: boolean;
  status: number;
  deadlines: { date: string | null; description: LocalizedText }[];
}

// What POST /documents returns immediately — OCR hasn't run yet (status is always Pending).
// Poll GET /documents/{id} for progress and completion.
export interface UploadDocumentResult {
  id: string;
  fileName: string;
  contentType: string;
  uploadedAt: string;
  status: number;
  totalPages: number;
}

export interface DocumentDetail {
  id: string;
  fileName: string;
  contentType: string;
  ocrText: string | null;
  uploadedAt: string;
  analysis: AnalysisResult | null;
  status: number;
  processedPages: number;
  totalPages: number;
  skippedPages: number;
  processingError: string | null;
}

export interface ChatMessage {
  id: string;
  role: number; // 0 = user, 1 = assistant
  content: string;
  createdAt: string;
}

export interface AuthUser {
  id: string;
  email: string;
  displayName: string;
  preferredLanguage: number;
  isAdmin?: boolean;
}

// GDPR Art. 15 data export (GET /api/users/me/export) — everything the account owns.
export interface ExportedChatMessage {
  role: number; // 0 = user, 1 = assistant
  content: string;
  createdAt: string;
}

export interface ExportedDocument {
  id: string;
  fileName: string;
  uploadedAt: string;
  ocrText: string | null;
  analysis: AnalysisResult | null;
  chatMessages: ExportedChatMessage[];
}

export interface AccountExport {
  userId: string;
  email: string;
  displayName: string;
  generatedAt: string;
  documents: ExportedDocument[];
}

// Business self-registration payload (category is a DOCUMENT_CATEGORY int).
export interface ProviderApplication {
  displayName: string;
  category: number;
  city?: string;
  phone?: string;
  whatsApp?: string;
  contactEmail: string;
  description: string;
}

// A pending application shown on the admin review page.
export interface PendingProvider {
  id: string;
  category: number;
  displayName: string;
  city: string | null;
  phone: string | null;
  whatsApp: string | null;
  contactEmail: string | null;
  blurb: LocalizedText;
  createdAt: string;
}

// A reviewed provider (live or deactivated) shown on the manage tab.
export interface ManagedProvider {
  id: string;
  category: number;
  displayName: string;
  city: string | null;
  phone: string | null;
  whatsApp: string | null;
  contactEmail: string | null;
  blurb: LocalizedText;
  isActive: boolean;
  priority: number;
  pricePerLead: number;
}

// Leads admin view.
export interface LeadSummary {
  providerId: string;
  displayName: string;
  monthCount: number;
  totalCount: number;
  pricePerLead: number;
  monthAmount: number;
  totalAmount: number;
  // Billing integrity: counts/amounts restricted to Converted-status leads.
  convertedMonthCount: number;
  convertedTotalCount: number;
  billableMonthAmount: number;
  billableTotalAmount: number;
  // Share of rated leads the user said helped (null until anything is rated).
  helpfulRate: number | null;
  // Needed to invoice this provider — null for admin-created providers that never self-registered.
  contactEmail: string | null;
}

// A persisted, immutable invoice snapshot for one provider + calendar month.
export interface Invoice {
  id: string;
  providerId: string;
  invoiceNumber: string;
  periodYear: number;
  periodMonth: number;
  currency: string;
  totalAmount: number;
  leadCount: number;
  status: number; // 0=Draft, 1=Sent, 2=Failed
  sentToEmail: string;
  generatedAt: string;
  sentAt: string | null;
  sendError: string | null;
}

export const INVOICE_STATUS_KEYS = ["invoice.draft", "invoice.sent", "invoice.failed"] as const;

// A lead's lifecycle status (LeadStatus backend enum, as an int on the wire).
export const LEAD_STATUS_KEYS = [
  "leadStatus.new", "leadStatus.contacted", "leadStatus.responded", "leadStatus.converted", "leadStatus.invalid",
] as const;

export interface RecentLead {
  id: string;
  providerId: string;
  displayName: string;
  category: number;
  urgency: number;
  ref: string | null;
  status: number;
  helpful: boolean | null;
  createdAt: string;
}
export interface LeadsOverview {
  summary: LeadSummary[];
  recent: RecentLead[];
}

// Admin funnel view — event counts (registered/verified/uploaded/analyzed) over a trailing window.
export interface EventCount {
  name: string;
  count: number;
}
export interface Funnel {
  sinceUtc: string;
  counts: EventCount[];
}
// One occurrence of a funnel event — email is null if the account has since been deleted.
export interface EventDetail {
  email: string | null;
  createdAt: string;
}

// A B2B/B2G tenant's public branding, resolved by slug (drives a white-labeled front end).
export interface OrganizationBranding {
  slug: string;
  name: string;
  logoUrl: string | null;
  primaryColorHex: string;
  accentColorHex: string | null;
  welcomeText: LocalizedText;
}

// A tenant row in the admin list. Includes branding so the usage dashboard can echo the
// tenant's own identity without a second round trip.
export interface OrganizationSummary {
  id: string;
  name: string;
  slug: string;
  isActive: boolean;
  createdAt: string;
  logoUrl: string | null;
  primaryColorHex: string;
  accentColorHex: string | null;
  welcomeText: string;
}

// Admin: create a new tenant. welcomeText fills all three language slots on the server.
export interface CreateOrganizationPayload {
  name: string;
  slug: string;
  logoUrl?: string | null;
  primaryColorHex: string;
  accentColorHex?: string | null;
  welcomeText: string;
}

// Admin: edit an existing tenant's branding. Slug is intentionally omitted — it's locked
// after creation since it drives already-shared ?org=slug links.
export interface UpdateOrganizationPayload {
  name: string;
  logoUrl?: string | null;
  primaryColorHex: string;
  accentColorHex?: string | null;
  welcomeText: string;
}

export interface CategoryCount { category: number; count: number }
export interface UrgencyCount { urgency: number; count: number }
export interface WeeklyCount { weekStart: string; count: number }

// Admin: one tenant's aggregate, anonymized usage — the renewal-justification dashboard.
export interface OrganizationStats {
  documentsProcessed: number;
  uniqueUsers: number;
  urgentCount: number;
  byCategory: CategoryCount[];
  byUrgency: UrgencyCount[];
  weeklyTrend: WeeklyCount[];
}

// Admin edit payload (description fills all three blurb languages on the server).
export interface UpdateProvider {
  displayName: string;
  category: number;
  city?: string;
  phone?: string;
  whatsApp?: string;
  contactEmail?: string;
  description: string;
  priority: number;
  pricePerLead: number;
}

// Server-side usage meter (replaces the old client-only lib/trial.ts localStorage counter).
export interface WalletBalance {
  balance: number;
  freeTierMonthlyCredits: number;
}
export interface UsageLedgerEntry {
  createdAt: string;
  kind: number; // 0=Grant 1=Consume 2=Expire 3=Refund 4=Sponsorship
  delta: number;
  operation: string;
  note: string;
  documentId: string | null;
}
export interface WalletSummary {
  balance: WalletBalance;
  history: UsageLedgerEntry[];
}

// A Terms/Privacy document body in one language (GET /api/legal/{kind}).
export interface LegalDocument {
  kind: string;
  version: number;
  body: string;
  effectiveAt: string;
}

// Sponsorship: someone else pays. Gifting credits from your own balance to someone else via a
// single-use redeem link (see backend Sponsorship entity).
export interface CreateSponsorshipResult {
  id: string;
  redeemToken: string; // shown exactly once — only its hash is ever stored server-side
  credits: number;
  expiresAt: string;
}
export interface SponsorshipSummary {
  id: string;
  credits: number;
  redeemed: boolean;
  createdAt: string;
  expiresAt: string;
}
export interface RedeemSponsorshipResult {
  creditsGranted: number;
  newBalance: number;
}

// A transcribed voice recording (the chat "ask out loud" mic button). Fills the chat input —
// never auto-sent, since Amharic ASR can be imperfect and auto-sending would spend a real chat
// credit on a question the user didn't ask.
export interface Transcript {
  text: string;
  locale: string | null;
}
