// Shared frontend types, mirroring the backend DTOs.

export type Language = "he" | "am" | "en";

// `flag` is an ISO country code used to load a flag image (emoji flags don't render on Windows).
export const LANGUAGES: { code: Language; label: string; rtl: boolean; flag: string }[] = [
  { code: "he", label: "עברית", rtl: true, flag: "il" },
  { code: "am", label: "አማርኛ", rtl: false, flag: "et" }, // Amharic (Ethiopic) is written LTR.
  { code: "en", label: "English", rtl: false, flag: "gb" },
];

// Only Hebrew is rendered right-to-left.
export function isRtl(language: Language): boolean {
  return language === "he";
}

// Maps frontend language codes to the backend Language enum (Hebrew=0, Amharic=1, English=2).
export const LANGUAGE_ENUM: Record<Language, number> = { he: 0, am: 1, en: 2 };

export type UrgencyLevel = "Low" | "Medium" | "High" | "Critical";

// A text generated by the backend in all three languages.
export interface LocalizedText {
  he: string;
  am: string;
  en: string;
}

// The chosen language's text, falling back to another language if it's blank.
export function loc(text: LocalizedText | undefined, language: Language): string {
  if (!text) return "";
  const order: Record<Language, Language[]> = {
    am: ["am", "en", "he"],
    en: ["en", "he", "am"],
    he: ["he", "en", "am"],
  };
  for (const l of order[language]) {
    if (text[l]?.trim()) return text[l];
  }
  return "";
}

// Document institution categories, mirroring the backend DocumentCategory enum (sent as ints).
export const DOCUMENT_CATEGORY = {
  Government: 0,
  Bank: 1,
  Insurance: 2,
  Employment: 3,
  Healthcare: 4,
  Municipality: 5,
  Other: 6,
} as const;

// Urgency string → backend enum int (the wire uses ints, like ChatMessage.role).
export const URGENCY_ENUM: Record<UrgencyLevel, number> = { Low: 0, Medium: 1, High: 2, Critical: 3 };

// A vetted professional shown as a sponsored referral.
export interface Provider {
  id: string;
  category: number;
  displayName: string;
  phone: string | null;
  whatsApp: string | null;
  city: string | null;
  blurb: LocalizedText;
}

export interface AnalysisResult {
  summary: LocalizedText;
  documentType: LocalizedText;
  // AI-classified institution category (DocumentCategory int) used to match referrals.
  category?: number;
  urgencyLevel: UrgencyLevel;
  keyPoints: LocalizedText[];
  requiredActions: { description: LocalizedText; isMandatory: boolean }[];
  deadlines: { date: string | null; description: LocalizedText }[];
  explanation: LocalizedText;
}

export interface DocumentSummary {
  id: string;
  fileName: string;
  contentType: string;
  uploadedAt: string;
  hasAnalysis: boolean;
}

export interface UploadDocumentResult {
  id: string;
  fileName: string;
  contentType: string;
  uploadedAt: string;
  pageCount: number;
  skippedPages: number;
}

export interface DocumentDetail {
  id: string;
  fileName: string;
  contentType: string;
  ocrText: string | null;
  uploadedAt: string;
  analysis: AnalysisResult | null;
}

export interface ChatMessage {
  id: string;
  role: number; // 0 = user, 1 = assistant
  content: string;
  createdAt: string;
}

export interface AuthUser {
  id: string;
  email: string;
  displayName: string;
  preferredLanguage: number;
  isAdmin?: boolean;
}

// Business self-registration payload (category is a DOCUMENT_CATEGORY int).
export interface ProviderApplication {
  displayName: string;
  category: number;
  city?: string;
  phone?: string;
  whatsApp?: string;
  contactEmail: string;
  description: string;
}

// A pending application shown on the admin review page.
export interface PendingProvider {
  id: string;
  category: number;
  displayName: string;
  city: string | null;
  phone: string | null;
  whatsApp: string | null;
  contactEmail: string | null;
  blurb: LocalizedText;
  createdAt: string;
}

// A reviewed provider (live or deactivated) shown on the manage tab.
export interface ManagedProvider {
  id: string;
  category: number;
  displayName: string;
  city: string | null;
  phone: string | null;
  whatsApp: string | null;
  contactEmail: string | null;
  blurb: LocalizedText;
  isActive: boolean;
  priority: number;
  pricePerLead: number;
}

// Leads admin view.
export interface LeadSummary {
  providerId: string;
  displayName: string;
  monthCount: number;
  totalCount: number;
  pricePerLead: number;
  monthAmount: number;
  totalAmount: number;
  // Billing integrity: counts/amounts restricted to Converted-status leads.
  convertedMonthCount: number;
  convertedTotalCount: number;
  billableMonthAmount: number;
  billableTotalAmount: number;
  // Share of rated leads the user said helped (null until anything is rated).
  helpfulRate: number | null;
}

// A lead's lifecycle status (LeadStatus backend enum, as an int on the wire).
export const LEAD_STATUS_KEYS = [
  "leadStatus.new", "leadStatus.contacted", "leadStatus.responded", "leadStatus.converted", "leadStatus.invalid",
] as const;

export interface RecentLead {
  id: string;
  providerId: string;
  displayName: string;
  category: number;
  urgency: number;
  ref: string | null;
  status: number;
  helpful: boolean | null;
  createdAt: string;
}
export interface LeadsOverview {
  summary: LeadSummary[];
  recent: RecentLead[];
}

// Admin edit payload (description fills all three blurb languages on the server).
export interface UpdateProvider {
  displayName: string;
  category: number;
  city?: string;
  phone?: string;
  whatsApp?: string;
  contactEmail?: string;
  description: string;
  priority: number;
  pricePerLead: number;
}
